# 基本信息
dataset: sthv2
data_path: ../sthv2
ckpt_path: ./checkpoints
exp_name: sthv2_finetune_from_sports1m # 实验名称

# 数据处理
train_batch_size: 30
val_batch_size: 8
workers: 16
clip_len: 16

# 路径加载控制
# 在监督学习模式下，模型加载由 model_ckpt_path 控制
checkpointer: false
test: false
final_test: false

# 训练设置
train: true
seed: 42
optimizer: SGD
lr: 0.0001 # 微调使用一个较小的学习率
weight_decay: 0.0005
momentum: 0.9
epoch_num: 80
patience: 20

# MMACTION2 配置
model_cfg_path: ../mmaction2/configs/recognition/c3d/c3d_sports1m-pretrained_8xb30-16x1x1-45e_ucf101-rgb.py
model_ckpt_path: ../pretrained_checkpoints/c3d_sports1m_pretrain_20201016-dcc47ddc.pth
#model_ckpt_path: ../pretrained_checkpoints/c3d_sports1m-pretrained_8xb30-16x1x1-45e_ucf101-rgb_20220811-31723200.pth
# 关键修改：sthv2 数据集有174个类别
num_classes: 20