# videomae_configs/kinetics_finetune_sthv2.yaml

# 基本信息
dataset: sthv2
data_path: ../sthv2
ckpt_path: ./checkpoints
exp_name: videomaev2_base_finetune_sthv2 # 实验名: 清晰标识模型、任务和数据集
model_type: videomae

# 数据处理
train_batch_size: 16
val_batch_size: 4
workers: 12
clip_len: 16

# 训练设置 (可以参考HMDB51的微调配置作为起点)
train: true
seed: 42
optimizer:
  type: 'SGD'
  lr: 0.004
  weight_decay: 0.05

epoch_num: 50
patience: 20

param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 50
    by_epoch: True
    milestones: [15, 35]
    gamma: 0.1

# MMACTION2 配置
# --- 模型结构配置：使用VideoMAEv2-Base的官方配置 ---
model_cfg_path: ../mmaction2/configs/recognition/videomaev2/vit-base-p16_videomaev2-vit-g-dist-k710-pre_16x4x1_kinetics-400.py
# --- 预训练权重：使用在Kinetics-400上预训练的权重 ---
model_ckpt_path: "../pretrained_checkpoints/vit-base-p16_videomaev2-vit-g-dist-k710-pre_16x4x1_kinetics-400_20230510-3e7f93b2.pth"
# --- 关键修改：确保类别数和特征维度正确 ---
num_classes: 20
# sthv2 数据集的类别数
embed_dim: 768        # VideoMAEv2-Base 模型的特征维度是 768