
# 基本信息
dataset: hmdb51
data_path: ../hmdb51
ckpt_path: ./checkpoints
exp_name: hmdb_random_al_timesformer_exp # 实验名，清晰标识模型和算法
model_type: timesformer
al_algorithm: random

# 数据处理 (采用Timesformer的配置)
train_batch_size: 8
val_batch_size: 4
workers: 8
clip_len: 8
num_each_iter: 5      # AL每轮选择的样本数

# 路径加载控制
load_weights: false
load_opt: false
exp_name_toload: null
exp_name_toload_rl: null # 非RL任务，设为null
snapshot: 0
checkpointer: true      # 建议在AL任务中开启，以保存每轮的状态
test: false
final_test: false
only_last_labeled: false

# 训练设置 (融合了监督学习和AL的设置)
train: true
seed: 42
optimizer:
  type: 'SGD'
  lr: 0.0005          # 采用为Timesformer优化的学习率
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True
epoch_num: 30         # 最终收敛训练的总轮数
patience: 10          # 早停耐心
al_train_epochs: 15   # AL循环中，每次微调的Epoch数

# 学习率调度器 (从Timesformer监督学习配置中借鉴)
param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 30 # 应与epoch_num匹配
    by_epoch: True
    milestones: [15, 25]
    gamma: 0.1

# Active Learning 参数 (从C3D random配置中借鉴)
initial_labeled_ratio: 0.05 # 假设初始标注比例
budget_labels: 578

# MMACTION2 配置
model_cfg_path: ../mmaction2/configs/recognition/timesformer/timesformer_spaceOnly_8xb8-8x32x1-15e_kinetics400-rgb.py
model_ckpt_path: ../pretrained_checkpoints/vit_base_patch16_224.pth
num_classes: 51
embed_dim: 768        # Timesformer (base)的特征维度