# timesformer_configs/imagenet_finetune_ucf101.yaml

# 基本信息
dataset: ucf101
data_path: ../ucf101
ckpt_path: ./checkpoints
exp_name: imagenet_finetune_ucf101 # 已按要求更新
model_type: timesformer

# 数据处理
train_batch_size: 8   # Timesformer模型较大，建议使用较小的batch size
val_batch_size: 4
workers: 8
clip_len: 8           # Timesformer通常使用8帧输入

# 路径加载控制
checkpointer: false
test: false
final_test: false

# 训练设置
train: true
seed: 42
optimizer:
  type: 'SGD'
  lr: 0.0005          # <-- 根据Kinetics配置和batch size进行了调整
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True      # <-- 借鉴自Kinetics配置
epoch_num: 20         # <-- 借鉴Kinetics的短周期训练策略，调整以适应小数据集
patience: 10          # <-- 早停耐心值

# 新增：学习率调度器 (借鉴自Kinetics配置)
param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 20
    by_epoch: True
    milestones: [10, 15] # 在第10和15个epoch降低学习率
    gamma: 0.1

# MMACTION2 配置
model_cfg_path: ../mmaction2/configs/recognition/timesformer/timesformer_spaceOnly_8xb8-8x32x1-15e_kinetics400-rgb.py
model_ckpt_path: ../pretrained_checkpoints/vit_base_patch16_224.pth
num_classes: 101
embed_dim: 768        # Timesformer (base)的特征维度是768