# timesformer_configs/ucf_har_config_mlp_baseline.yaml

# ===================================================================
#                       通用配置 (对所有阶段生效)
# ===================================================================
# --- 基本信息 (参考 timesformer_configs/imagenet_random_ucf101.yaml) ---
dataset: ucf101
data_path: ../ucf101
ckpt_path: ./checkpoints
# --- 实验名: 清晰地标识模型、数据集、奖励模型和工作流 ---
exp_name: ucf101_alrm_mlp_baseline_timesformer_exp
# --- 关键修改: 指定模型、AL算法和奖励模型 ---
model_type: timesformer
al_algorithm: dqn
reward_model_type: mlp

# --- 数据处理 (参考Timesformer配置) ---
train_batch_size: 8   # ViT类模型建议使用较小的batch size
val_batch_size: 4
workers: 8
clip_len: 8           # Timesformer通常使用8帧作为输入
num_each_iter: 20     # UCF101 每轮选择的样本数

# --- 路径加载控制 (保持默认) ---
load_weights: false
load_opt: false
exp_name_toload: null
exp_name_toload_rl: null
snapshot: 0
checkpointer: 1
test: false
final_test: false
only_last_labeled: false

# ===================================================================
#             阶段 1 & 3: 主动学习与RL智能体训练
# ===================================================================
# --- 训练设置 (参考 timesformer_configs/imagenet_random_ucf101.yaml) ---
train: true
seed: 42
# --- 为Timesformer设置优化器和学习率调度器 ---
optimizer:
  type: 'SGD'
  lr: 0.0005
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True
epoch_num: 30         # 最终收敛训练的总轮数
patience: 10          # 早停耐心
al_train_epochs: 15   # AL循环中，每次微调的Epoch数
param_scheduler:
  - type: 'MultiStepLR'
    begin: 0
    end: 30
    by_epoch: True
    milestones: [15, 25]
    gamma: 0.1

# --- DQN 智能体训练参数 (参考 c3d_configs/hmdb_har_config_mlp_baseline.yaml) ---
lr_dqn: 0.0001
gamma_scheduler_dqn: 0.99
rl_pool: 10
rl_buffer: 100
dqn_bs: 20            # DQN批大小通常与每轮选择数(num_each_iter)保持一致
dqn_gamma: 0.99

# --- Active Learning 参数 (参考 timesformer_configs/imagenet_random_ucf101.yaml) ---
initial_labeled_ratio: 0.05
budget_labels: 950

# --- MMACTION2 模型配置 (参考 timesformer_configs/imagenet_random_ucf101.yaml) ---
model_cfg_path: ../mmaction2/configs/recognition/timesformer/timesformer_spaceOnly_8xb8-8x32x1-15e_kinetics400-rgb.py
model_ckpt_path: ../pretrained_checkpoints/vit_base_patch16_224.pth
num_classes: 101
embed_dim: 768        # Timesformer (base)的特征维度是768

# ===================================================================
#         阶段1数据收集 & 阶段3 RL状态 使用的特征提取器配置
# ===================================================================
# --- 开启所有特征以获得最丰富的奖励模型输入 ---
use_statistical_features: false
use_diversity_feature: false
use_representativeness_feature: false
use_prediction_margin_feature: false
use_labeled_distance_feature: false
use_neighborhood_density_feature: false
use_temporal_consistency_feature: false